name: sensitive_content_analysis_example
description: "Demonstrates how to use the sensitive_content_analysis plugin."
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  sensitive_content_analysis:
    path: ../
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.7
  file_selector: ^1.0.2
  path_provider: ^2.1.2
  dio: ^5.4.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true