name: sensitive_content_analysis
description: "Flutter package for interacting with Apple's Sensitive Content Analysis."
version: 0.0.3
homepage: https://github.com/jonafeucht/sensitive_content_analysis

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: SensitiveContentAnalysisPlugin