name: sensitive_content_analysis
description: "Dart plugin for interacting with Apple's Sensitive Content Analysis Framework."
version: 1.0.2-rc.1
homepage: https://github.com/jonafeucht/sensitive_content_analysis

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: SensitiveContentAnalysisPlugin
      macos:
        pluginClass: SensitiveContentAnalysisPlugin