name: sensitive_content_analysis
description: "Dart package for interacting with Apple's Sensitive Content Analysis Framework."
version: 0.0.7
homepage: https://github.com/jonafeucht/sensitive_content_analysis

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: SensitiveContentAnalysisPlugin