name: Flutter CI
 
on:
  push:
    branches: ["main", "master", "dev"]
  pull_request:
    branches: ["main", "master", "dev"]
 
jobs:
  test:
    name: Unit & Widget Tests
    runs-on: macos-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
 
      - name: Install dependencies
        run: flutter pub get
        working-directory: example

      - name: Generate mocks (build_runner)
        run: dart run build_runner build --delete-conflicting-outputs
        working-directory: example

      - name: Auto-format code
        run: dart format .
        working-directory: example
 
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
        working-directory: example
 
      - name: Analyze code (dart analyze)
        run: flutter analyze
        working-directory: example
 
      - name: Run tests with coverage
        run: flutter test --coverage
        working-directory: example